### PR TITLE
Solomon Jin  html-web-page

### PR DESCRIPTION
**Pull request by solomonjin**
Screen Shot 2021-05-04 at 3 38 39 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Solomon! Please attach a screenshot of your output to the pull request

**Comment by solomonjin** [comment]
Screen Shot 2021-05-04 at 3 38 39 PM

**Review by codingcodymiller — APPROVED** [review]
Nice work!!!

**Pull request merged**
